### ISSUE TITLE
Doesn't show standart methods

### ISSUE THREAD

**Issue by Raensul** [shawncplus/phpcomplete.vim#107]
Please help me to understand what am i doing wrong. I have _tags_ file by phpctags. If I type code like this
`$a = User::`
 and press ctrl+space, autocomplete works well and I am seeing all static methods defined in class User. But if I am writing code like
```
$b = new UserController;
$arr = $b->
```
and press ctrl+space nothing is happening.

**Comment by Raensul** [comment]
Thank you for reply.
I made tags file in the directory where class is defined and it is ok now.
Sorry to disturb you.

**Comment by complex857** [comment]
No worries, I'm glad you managed to figure it out. :+1:
