### ISSUE TITLE
Little update to the docs about universal tags

### ISSUE THREAD

**Issue by stronk7** [shawncplus/phpcomplete.vim#124]
Hi!

In the [Getting better tags](https://github.com/shawncplus/phpcomplete.vim/wiki/Getting-better-tags) page, when talking about universal ctags... you point to [#815](https://github.com/universal-ctags/ctags/issues/815).

That issue has been already fixed and you can avoid the double backslashes with the `--output-format=e-ctags` option. (known caveat: ctags will skip any name having whitespace - that is the original use the backslashes have in ctags, but usually we don't have class/method/var names with whitespaces so...).

It's working awesomely here, now jumping to the correct definitions, finding parents... so worth commenting the option, surely.

Thanks for all the effort! Ciao :-)

**Comment by complex857** [comment]
Hi @stronk7!

Wonderful news! I've updated the readme (remove the mention of the escaping issue and add the flag to the example).

Thank you very much for bringing my attention to this 👍
