### ISSUE TITLE
omnicomplete not showing typed properties

### ISSUE THREAD

**Issue by levigutt** [shawncplus/phpcomplete.vim#131]
I can't get the omnicomplete menu to show typed properties. 

Generating a tags file did not seem to help, even I can see it contains the typed properties. 

**example of issue:**

```php
class Thing {
    public $a;
    public $b;
    public string $c;
}
$thing = new Thing();
$thing->
```

with the cursor placed after the arrow `$thing->` doing `c-x` `c-o` shows the omnicomplete menu, but property `c` is missing:

![image](https://github.com/vim/vim/assets/16719598/209e0a95-09c8-4eed-9afb-7ab20f836a00)

**Comment by levigutt** [comment]
where in the source are these patterns?

**Comment by levigutt** [comment]
does this plugin not load from the tags file?

**Comment by complex857** [comment]
Added support the new `readonly` keyword alongside of nullable types (at least for completion).

Using the hinted types will have to be done still. Lemme know if this works for you and feel free to re-open the ticket if you see something wrong

**Comment by kfwebmaster** [comment]
It works! 👍 

edit: never mind the error, I installed it the wrong directory
works perfectly when installed correctly 💯

**Comment by chrisbra** [comment]
hi guys,
just want to remind you to send an update to vim/vim if you think this can and should be included with Vim at some point :) thanks!

**Comment by complex857** [comment]
Hi @chrisbra! 
Excuse my ignorance, but do you know what's the system now to send in patches for runtime updates? 

The version included with the runtime install is a derivative of this repo's code indeed (stripped down a bit, different code formatting, etc), I used to just email patches to Bram Moolenaar, but sadly this is not an option anymore.

**Comment by chrisbra** [comment]
no problem.
There are several options (in the order of preference):
- create a PR at the vim repository
- send via mail via the vim-dev mailinglist
- send directly to me

Either one should work.

Thanks!
