### ISSUE TITLE
Merge into/with official phpcomplete.vim file

### ISSUE THREAD

**Issue by blueyed** [shawncplus/phpcomplete.vim#5]
It would be nice to get the improvements of this project (which appears to be a fork from the official phpcomplete.vim file) back into Vim itself.

Please consider submitting a patch to Vim itself and helping with maintaining it from there.

Thanks!

**Comment by lvht** [comment]
May be you should try the https://github.com/phpvim/phpcd.vim . A new phpcomplete extended version based on the PHP's Reflection.

**Comment by complex857** [comment]
I'll go aheadand close this ticket now. The currently bundled phpcomplete is basically this codebase now (with a little leas bells and whistles), so in one word: Done (-:
