### ISSUE TITLE
Flashing gui widow tabs when doing completion

### ISSUE THREAD

**Issue by mriva** [shawncplus/phpcomplete.vim#61]
I updated today phpcomplete to the current version and noticed something it wasn't happening with the old one: every time a completion is attempted a new window tab appears then disappears immediately. Looking at the difference between the new and old versions I found out it's due to these lines:

2310     silent! tab 1new  
2651     silent! tab 1new

if I change "tab" with "below" it works as it used to. The completion then works, but that quick tab bar flash is very annoying, can this be fixed? Or how can I work around this without editing the code of the plugin itself?

**Comment by complex857** [comment]
Thank you for tracing down to a specific commit!

Could you check if enabling [`lazyredraw`](http://vimdoc.sourceforge.net/htmldoc/options.html#%27lazyredraw%27) makes these flickers disappear? As far as I can tell from the docs that should work.
I myself couldn't been to be able to reproduce it with either console vim or gvim. If lazyredraw won't solve it, could give me your [`guioptions`](http://vimdoc.sourceforge.net/htmldoc/options.html#%27guioptions%27) (the option `e` is my main suspect)?

**Comment by mriva** [comment]
I already had `lazyredraw` enabled so that doesn't fix it. This is my current `guioptions`

    guioptions=aegirLt 

I tried removing the `e` which makes it better (the tab bar doesn't show up at all) but I can still see a flicker, like an old terminal slow screen refresh. Using `below` instead of `tab` gets rid of the problem completely.

Anyway I'm using gvim (gtk) 7.4 on linux.

**Comment by complex857** [comment]
I see. I'm too gtk gvim + linux, with the version 7.4.608, but with completely empty guioptions (`set guioptions=`).
This change was introduced to solve #57, but looks like I'll have revert this change and reexamine the possible workarounds. Thank you for reporting this.

**Comment by complex857** [comment]
@mriva: I've pushed a commit which reverts the offending commit, this should solve this issue, please give the new master version a try.

**Comment by mriva** [comment]
The latest commit does indeed solve the issue, thanks for looking into this
