### ISSUE TITLE
Class member variables not completing correctly

### ISSUE THREAD

**Issue by vbjordan** [shawncplus/phpcomplete.vim#65]
I'm having issues getting completion to work on class member variables that are objects; i.e.:

```
<?php

class ClassA
{
  /* @var ClassB */
  private $classb;

  public function a()
  {
    /* completion works */
    $b = new ClassB();
    $b->bMethod();

    /* completion works */
    /* @var ClassB $c */
    $c->bMethod2();

    /* completion does not work */
    $this->classb->

  }
}
```

Test repo here: https://github.com/vbjordan/phpcomplete-test

ctags call with the patched ctags: ctags -R  --fields=+aimS --languages=PHP

**Comment by complex857** [comment]
I've looked into this and it seems to me that at this moment, the only docblock style recognized by the plugin is the longer, multi line one for the class level things like methods and properties. So for example, if you write it like this:
 
    class ClassA
    {
	    /**
	     * @var ClassB
	     */
	    private $classb;
    }
The plugin will pick up the hint. I don't see a reason why the shorter pattern shouldn't work but it will need some tweaking in the [phpcomplete#GetDocBlock](https://github.com/shawncplus/phpcomplete.vim/blob/12d56a37949707f4803436af001802c4cb00cab7/autoload/phpcomplete.vim#L2470) method.

Thank you for reporting this!

**Comment by vbjordan** [comment]
Great, thanks for looking into it. I can confirm it does work with the longer version of the docblock. I thought I'd tried that but I guess I hadn't.

**Comment by complex857** [comment]
I've pushed a commit that should add support for the one-line style. Please give it a try and let me know if it's not working properly.
