### ISSUE TITLE
Cannot complete classes/methods from a namespace inside a control structure inside a closure

### ISSUE THREAD

**Issue by shawncplus** [shawncplus/phpcomplete.vim#67]
If you are inside of a closure and have a control structure inside that (foreach/if/etc) and try to complete classes/methods from namespaces specified by the `use` statements it will not work.

It seems to lie in the `"clear out classes, functions and other blocks` area inside `phpcomplete#GetCurrentNameSpace`

Example

    <?php
    
    use SomeParentNS\SomeChildNS;

    $testFunc = function () {
        $blah = new SomeChildNS\SomeClass();
        $blah->stuff(); // completes fine
        foreach([] as $a) {
            $test = new SomeChildNS\SomeClass();
            $test-> // can't complete
        }
    };

**Comment by shawncplus** [comment]
My first thought is to remove the check for `function` inside the regex but I have to imagine that will cause issues so second thought would be to write a second regex which checks for named functions

**Comment by hernol** [comment]
Hi all.
I'm running master and this doesn't seems to be working.
My problem is when running a closure with a typed parameter like this:
```php
use Illuminate\Database\Schema\Blueprint;

class SomeClass {
  $closure = function(Blueprint $table) {
    $table->
  }
}
```
trying to autocomplete the table Blueprint object.

If it's just my problem and I'm missing something, please tell me so. If this is happening somebody else, I'll try to fix it.
Thanks.

**Comment by complex857** [comment]
From what i can see the class `Blueprint` is imported from a third party library. 

For the plugin to work it have to have the classes in question in the tag files and need to be able to actually open the source file of the class to gather the completions. So It could be two things here:

1. The library is not indexed in the tag files (framework stuff can be if it's loaded with composer or such)
2. The files are not reachable from the tag files

What you could try to check if you run `:tselect Blueprint` to see if it returns anything and if it does the `file` column is something reachable.
