### ISSUE TITLE
function paramaters from interface in autocomplete

### ISSUE THREAD

**Issue by koenhoeymans** [shawncplus/phpcomplete.vim#71]
Referencing this topic:

https://github.com/shawncplus/phpcomplete.vim/issues/15

I think the regex should also look for a `;` at the end of the line in case it reads the function parameters from an interface. In my case there were no function parameters given and adjusting `\({\|\_$\)')` to `\({\|;\|\_$\)')` at the end of line 957 in `phpcomplete.vim` seems to solve this for me.

**Comment by complex857** [comment]
I think i understand the what you are saying, so you have a snippet like this:

```php
interface FooAble {
    function foo($bar = 42);
}
```
And the current regexp is looking for a `{` somewhere which is not there since function in interfaces has no body.
Am i getting this right?

**Comment by koenhoeymans** [comment]
Yes that's it, and as a result no function arguments in the autocomplete popup.

**Comment by complex857** [comment]
Great, i has a commit ready but i don't want to steal your tunder if you want to send a pull request (-:

**Comment by koenhoeymans** [comment]
I'll pull your commit. Thanks for fixing.

**Comment by complex857** [comment]
Al right, I've pushed my patch, please check it out. It's nice to see that interfaces are getting a little attention, thanks.

**Comment by koenhoeymans** [comment]
Works as expected. Thanks.
