### ISSUE TITLE
Support to neobundle

### ISSUE THREAD

**Issue by Soufraz** [shawncplus/phpcomplete.vim#73]
Hello,
Can I install the plugin with neobundle? If not, it's possible install the phpcomplete manually?
Waiting.. Thanks advance.

**Comment by complex857** [comment]
Hi,
Yes of course you can, (in fact i'm using [NeoBundle myself](https://github.com/complex857/dotvim/blob/cd6e759b60d90430bd89cb3286728985a8af3ab9/vimrc)), just add the github style package name like any other plugin and you are good to go:
```
NeoBundle 'shawncplus/phpcomplete.vim'
```

**Comment by Soufraz** [comment]
Ok.. The installation works fine. But, when typing something function of php or start to write $this inside some class, nothing happens. 
Am I missing something?

**Comment by complex857** [comment]
The plugin doesn't do "complete-as-you-type" style functionality if this is what you are thinging of.

The usual way to invoke the completion plugins is to ask for "[omni completion](http://vim.wikia.com/wiki/Omni_completion)" with <kbd>ctrl</kbd>+<kbd>x</kbd><kbd>o</kbd> in insert mode. This invokes the function in the "`:omnifunc`" option, which should be set to `phpcomplete#CompletePHP`. 
This setting should already be set up by the default fttype plugin for php, so you shouldn't need to worry about it. 
However you can check it's value by opening up a php file and type `:set omnifunc` and hit enter, and see what's printed on the status line. You should see `omnifunc=phpcomplete#CompletePHP`.

**Comment by complex857** [comment]
I'm gonna close this now, if you have more questions let me know.
