### ISSUE TITLE
support for frameworks/library keywords?

### ISSUE THREAD

**Issue by gbell12** [shawncplus/phpcomplete.vim#74]
Thanks for this project Shawn!

I'm trying to include Zend Framework 2's keywords in my list of completion candidates.

Currently I'm using phpcomplete with Omnicomplete and ctags with 'complete' (via dictionary) separately.  It's awkward.

1) Type Abstract[tab]
2) Omnicomplete tells me "pattern not found" (in the currently open buffers)
3) Slap forehead for not remembering this always happens
4) Hit Ctrl-N to use the exuberant ctags file I generated for ZF2 that's in my project root
5) Nothing happens.  Slap forehead for not remember that this always happens.  Also try to slap Vim for silently failing for No Good Reason.  Realize Vim is just a program.
6) Backspace
7) type "t" and then Ctrl-N
8) Get nice list of all of ZF2's Abstract classes.

Surely I'm doing this wrong?  Should/does phpcomplete look up tags in frameworks too?

**Comment by shawncplus** [comment]
it'll complete any classes that are inside the tags file. When you're generating the tags just do it from your project root recursively, if the Zend classes are in `vendor/` or `lib/` or whatever those will be picked up, no need to have separate tags files. Just use omnicompletiong, no need to use dictionary completion for one and omnicompletion for another

**Comment by gbell12** [comment]
That makes sense, thanks.
Do you know if the out from exuberant ctags is also usable by phpcomplete or only the ctags fork you reference in your docs?

**Comment by shawncplus** [comment]
You  have to use the fork from the docs if you want to reference code with namespaces which almost certainly you do. Once you build the fork you use it just like normal ctags

**Comment by gbell12** [comment]
Beaut, many thanks.
