### ISSUE TITLE
Request for better introduction documentation

### ISSUE THREAD

**Issue by ipsod** [shawncplus/phpcomplete.vim#75]
I wasn't able to get this setup the first time I tried, and I think documentation would have helped.

The most important two things to add to docs are these:
Step 1: Generate ctags in your project's root directory. (maybe with instructions as to how)
Step 2: C-x C-o to autocomplete.

Also of interest is how to use an inotifywait script to automatically generate ctags when necessary.  Even if the docs don't say exactly how, they can say that it's possible, and maybe provide some useful links.

Also, asciinema demonstrations of the features would be awesome, and maybe a mention that it works with frameworks, and list a few (laravel, symfony, whatever) - I had given up on any Vim autocompletion actually supporting a framework/Composer development environment.

**Comment by glensc** [comment]
Totally agree, as never being using autocomplete in vim, don't even know how to use this phpcomplete.vim other than having it setup with Bundle!

**Comment by alexander-alzate** [comment]
Same think here!, Thanks to ipsod to steps 1 and 2.

Actually, I think step 1 should be ran automatically.

**Comment by complex857** [comment]
@ipsod, I know this has been too long, but with the kind help of @gabesullice, we've made some inroads in form of the [GUIDE.md](https://github.com/shawncplus/phpcomplete.vim/blob/master/GUIDE.md) file. I'm gonna close this ticket, but feel free to add any feedback.
