### ISSUE TITLE
neocomplete breaks phpcomplete.vim

### ISSUE THREAD

**Issue by markwu** [shawncplus/phpcomplete.vim#76]
Hi,

I report this issue in neocomplete.vim, but I think I should let you know.

https://github.com/Shougo/neocomplete.vim/issues/467

This bug due to phpcomplete.vim use a new `phpcompletetempbuffer` window/buffer to get current class and namespace. 

The windows manipulation seems conflict with neocomplete.vim.

Although I can use the following settings in neocomplete.vim to work around this issue, but I lost the power of neocomplete.vim.

```
    if !exists('g:neocomplete#force_omni_input_patterns')
      let g:neocomplete#force_omni_input_patterns = {}
    endif
    let g:neocomplete#force_omni_input_patterns.php = '[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
```

Is there any other way to work around this?

BTW, it works well under YouCompleteMe.

**Comment by complex857** [comment]
Thank you for letting me know about this. I myself don't use neocomplete, I'll have to look into this but I'm pretty sure that this should not be happening.

**Comment by Shougo** [comment]
Hi, neocomplete author.
neocomplete cannot support the omnifunc.
Because, it uses temporary buffer and must switch it.
It causes the error.

**Comment by Shougo** [comment]
@complex857 Sorry, it seems neocomplete uses InsertCharPre event.
I will remove the feature.

**Comment by markwu** [comment]
Great thanks for both great plugins authers, the problem solved. I'll close this issue.
