### ISSUE TITLE
Disable when writing comments?

### ISSUE THREAD

**Issue by lukepass** [shawncplus/phpcomplete.vim#80]
Hello,  
is it possible to disable this plugin *when writing a PHP comment*? It can considerably slow down the writing process since it is constantly popping up.

Thanks.

**Comment by complex857** [comment]
Hmm, i assume you have something like YCM or Neocomplete which auto-triggers the plugin?
Can you check if there's a way to configure that plugin so it won't trigger completion in that case?

I myself find it useful when typing out docblocks (think like `@param` or `@return`), but i'm hitting <kbd>ctrl</kbd>+<kbd>x</kbd><kbd>o</kbd>  by hand. What should be possible to implement is to bail out early if it detects it's in a comment region, even tough the plugin still be called non the less.

**Comment by lukepass** [comment]
Yes, I am using Neocomplete. I mapped F2 to Neocomplete lock function (no autocomplete) and I am pressing it when writing long comments.

**Comment by complex857** [comment]
That sounds pretty annoying to be honest (-: There's currently no way to disable completion inside comments, but i guess this could be implemented.
