### ISSUE TITLE
Installing universal-ctags/ctags instead of the patched php?

### ISSUE THREAD

**Issue by Ilyes512** [shawncplus/phpcomplete.vim#85]
So I found out about ctags not being actively maintained and that it missed all "new" syntaxes (it does not even support namespaces).

So I found 2 alternatives:

- https://github.com/b4n/ctags/tree/better-php-parser
- https://github.com/universal-ctags/

So in this wiki page you recommend using @b4n's branch, but I was wondering if the universal-ctags would be better seeing that b4n is also actively helping that project (https://github.com/universal-ctags/ctags/commits?author=b4n).

Not sure if the universal one also contain the new flags (aimS).

**Comment by complex857** [comment]
I didn't know about this universal ctags project, thanks for letting me know. I've updated the wiki page's intro to include this link too. To me it seems it should support the same flags and have better php7 support too.

Thank you for letting me know!
