### ISSUE TITLE
View the builtin function reference in preview pane

### ISSUE THREAD

**Issue by gezpage** [shawncplus/phpcomplete.vim#86]
Really great work on this plugin guys, makes Vim so much better when working with PHP.

So I've been trying to find out how I can view the built in PHP functions (https://github.com/shawncplus/phpcomplete.vim/blob/master/misc/builtin.vim) inside a preview / scratch window. This would be very useful for checking function call parameters instead of going to php.net.

Currently I can use omni completion to show matches on built in php functions, and the currently selected match is shown in the preview pane (type preg_ then `<c-x><c-o`> for example), great. However if there's only one match it will simply complete it and show "The only match" in the status line, the preview window will not appear so I can't see the function reference.

I've tried doing `:ptag strpos` but it just says tag not found, as it's not in the tags file. There appears to be no way of doing a lookup in the builtin functions that come with phpcomplete.

Any help with this would be fantastic.

Thanks!

**Comment by complex857** [comment]
I think you are looking for the `menuone` option for the [`completeopt`](http://vimdoc.sourceforge.net/htmldoc/options.html#%27completeopt%27) setting. This should make the preview window and menu show up even if you have only one match.
So something like this: https://asciinema.org/a/5v536a2aaqw01q21pnmmp66wn
(Side note: the demonstration probably unnecessary, but i really adore this asciinema project :D).

Check out this project too: https://github.com/vim-scripts/phpmanual Full manual page transfers to vim docs pages on the built-on <kbd>shift</kbd>+<kbd>k</kbd> bindings.

**Comment by gezpage** [comment]
Hey thanks for this, works a treat. Also the phpmanual plugin is a good find, I had been looking for something similar, and up to date, and this even includes PHP 7 functions.

Cheers!
