### ISSUE TITLE
`$this->` autocompletion not working outside namespaces

### ISSUE THREAD

**Issue by cprn** [shawncplus/phpcomplete.vim#87]
### Example
I might be stupid here but consider the following two almost identical files:
- working autocompletion inside the `Facebook\WebDriver\Remote` namespace:
```php
<?php
namespace Facebook\WebDriver\Remote;

$drv = RemoteWebDriver::create();
$drv-><C-x><C-o> # list of methods
```
- not working autocompletion in global namespace:
```php
<?php
use Facebook\WebDriver\Remote\RemoteWebDriver;

$drv = RemoteWebDriver::create();
$drv-><C-x><C-o> # pattern not found
```

The above is a minimal example from the bigger code sample that runs correctly (in both cases). Note the following works correctly as well (in both cases):
```php
RemoteWebDriver::<C-x><C-o> # list of methods
```

### Prerequisites
- dependencies:
```sh
mkdir test && cd test
curl -sS https://getcomposer.org/installer | php # composer local install
./composer.phar require facebook/webdriver       # selenium webdriver
```
- installed `shawncplus/phpcomplete`
- installed [patched ctags](https://github.com/shawncplus/phpcomplete.vim/wiki/Patched-ctags)
- generated `tags` file: `ctags -R --fields=+aimS --languages=php`

**Comment by complex857** [comment]
Thank you very much for the exemplary bug report!
I think I've fixed the bug, please try again with the current master.

**Comment by cprn** [comment]
Awesome! I confirm current master works without a problem with global namespace.
