### ISSUE TITLE
No completion for type operator `instanceof`

### ISSUE THREAD

**Issue by codeinabox** [shawncplus/phpcomplete.vim#88]
Should it produce a completion for the type operator `instanceof`?

**Comment by complex857** [comment]
No, at this moment that context is not supported, but it's a good suggestion.

**Comment by complex857** [comment]
I've added some support for the `instanceof` context, Unfortunately fqcns are hard to get from tags, so you will need to ask more than one completion after an another if you have names as well in your class names, but i think still better than nothing.

Let me know if you find it useful or not.
