### ISSUE TITLE
Universal Ctags instead of Patched Ctags

### ISSUE THREAD

**Issue by lukepass** [shawncplus/phpcomplete.vim#89]
Hello, do you think [this mantained ctags implementation](https://github.com/universal-ctags/ctags) (Universal Ctags) would work instead of the recommended Patched Ctags file?
I think it would be better to stay with a mantained version instead of a single file.

Thanks.

**Comment by complex857** [comment]
I'm absolutely certain that it will work, I've included a passage in the wiki page about it before [on request](https://github.com/shawncplus/phpcomplete.vim/issues/85). 
You are right though, it's probably time to decommission the old patched ctags wiki page and just direct people to the ctags.io project. Just need to get into writing mode :-D.

Would be nice if these ctag projects would be able to grab the docblocks as well, I've made the patches for the old version and sent out pull requests but didn't catch on.

**Comment by complex857** [comment]
I've revamped the docs and the wiki page. Should be clear enough now. Please feel free to correct my English as you see fit.

**Comment by lukepass** [comment]
Thank you!

**Comment by complex857** [comment]
I've ended up revamping the docs again. It turns out that ctags.io have some issues with `\` that the plugin doesn't really like that much. I've tried to make the wiki page more understandable.
