### ISSUE TITLE
YouCompleteMe Conflict

### ISSUE THREAD

**Issue by LukeHowellDev** [shawncplus/phpcomplete.vim#93]
When using `phpcomplete` with YouCompleteMe the completion while typing provided by YouCompleteMe is gone.  

The autocomplete will appear but when you start typing it goes away.  Any luck with working with YouCompleteMe?

**Comment by complex857** [comment]
I personally never tried YCM with this plugin. If I'm not mistaken it should be able to get the completions from normal `omnifunc` sources, so in theory there's no reason for it not to work.
You can try to disable a cache around omnifunc results with `let g:ycm_cache_omnifunc = 0` which according to the [docs](https://github.com/Valloric/YouCompleteMe#the-gycm_cache_omnifunc-option) might affect the results adversely.
Let me know if that helps so i can amend the docs on my part.

**Comment by markwu** [comment]
I use both NeoComplete and YouCompleteMe, but I never meet this problem in YouCompleteMe,

Here comes with my configuration:

```vim
let g:ycm_seed_identifiers_with_syntax = 1
let g:ycm_collect_identifiers_from_tags_files = 1

let g:ycm_key_list_select_completion = ['<TAB>', '<C-N>', '<Down>']
let g:ycm_key_list_previous_completion = ['<S-TAB>', '<C-P>', '<Up>']
let g:ycm_key_invoke_completion = '<C-F>'
```

Maybe you would like to give it a try.

**Comment by complex857** [comment]
I'm gonna close this one for housekeeping.
@LukeHowellDev: Let us know if you are still having a problem.
