### ISSUE TITLE
Commit 3125c5a will break vim undo

### ISSUE THREAD

**Issue by markwu** [shawncplus/phpcomplete.vim#98]
I never know this bug exist, until today.

phpcomplete.vim will break vim undo after commit 3125c5a. Here comes the screencast:

commit 3125c5a - undo break, the last line still there 
![phpcomplete-3125c5a](https://cloud.githubusercontent.com/assets/196861/22893904/1343b42c-f252-11e6-8af2-c776aa194f48.gif)

commit 388c5f7 (previous commit) - undo works, without any problems
![phpcomplete-388c5f7](https://cloud.githubusercontent.com/assets/196861/22893929/25053b68-f252-11e6-9e7a-a315b51d82bc.gif)

Here comes my minimal vimrc
``` vim
set nocompatible
filetype off

execute 'source ~/.vim/bundle/vim-plug/plug.vim'
call plug#begin('~/.vim/bundle/')

Plug 'junegunn/vim-plug'

" Put your bundle below here
Plug 'maralla/completor.vim'
Plug 'shawncplus/phpcomplete.vim'
" Put your bundle above here

call plug#end()

syntax on
filetype plugin indent on

" Put your plugin settings below here
" completor
set completeopt-=preview
set completeopt+=menu,menuone,noinsert,noselect
set shortmess+=c

let g:completor_php_omni_trigger = '([$\w]{2,}|use\s*|->[$\w]*|::[$\w]*|implements\s*|extends\s*|class\s+[$\w]+|new\s*)$'

imap <expr><TAB> pumvisible() ? "\<C-N>" : "\<TAB>"
smap <expr><TAB> pumvisible() ? "\<C-N>" : "\<TAB>"
imap <expr><S-TAB> pumvisible() ? "\<C-P>" : "\<S-TAB>"
smap <expr><S-TAB> pumvisible() ? "\<C-P>" : "\<S-TAB>"
imap <expr><CR> pumvisible() ? "\<C-Y>\<CR>" : "\<CR>"
smap <expr><CR> pumvisible() ? "\<C-Y>\<CR>" : "\<CR>"
"Put your plugin settings above here

```

My vim is Macvim 8.0.324
OS is OSX 10.11.6

**Comment by complex857** [comment]
Hmm, this is bad. I'm not sure what to look for though

**Comment by complex857** [comment]
I've done some more testing, on my home machine, VIM 7.4 + Included patches: 1-989 (linux) I can't seem to reproduce it.

**Comment by complex857** [comment]
@markwu: I think vim master have a fix for this bug now, please see this patch: https://github.com/vim/vim/commit/d56a79d3396cf70861b7f739a3c400db91ce7b70

I've re-tried this with macvim build 8.0 1-341 and it seems to be fixed for me.

**Comment by markwu** [comment]
Sorry,  a little busy recently. 

I just check out the master branch of https://github.com/macvim-dev/macvim , it does not merge this patch yet (It is vim 8.0 patch 329 now), I will test this issue again after macvim merge this patch.

Thanks your information.

**Comment by markwu** [comment]
I tested this issue with macvim 8.0.363, this bug does not exist anymore. I'll close this issue. Thanks for your help.
